// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/invention": {
            "get": {
                "description": "Get all inventions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api/v1"
                ],
                "summary": "Get",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entity.Invention"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add a new invention with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api/v1"
                ],
                "summary": "Add",
                "parameters": [
                    {
                        "description": "Invention entity",
                        "name": "invention",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Invention"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data is valid",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/invention/{id}": {
            "get": {
                "description": "Get an invention by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api/v1"
                ],
                "summary": "Get",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Invention ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Invention"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing invention with the input payload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api/v1"
                ],
                "summary": "Update",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the invention to update",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Invention entity",
                        "name": "invention",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Invention"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Invention updated successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an existing invention by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "api/v1"
                ],
                "summary": "Delete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the invention to delete",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Invention deleted successfully",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Invention": {
            "type": "object",
            "required": [
                "inventor"
            ],
            "properties": {
                "date": {
                    "type": "string",
                    "example": "2024-04-30T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "maxLength": 300,
                    "minLength": 3,
                    "example": "This is an amazing invention that will revolutionize the world."
                },
                "id": {
                    "type": "string",
                    "example": "123"
                },
                "inventor": {
                    "$ref": "#/definitions/entity.Inventor"
                },
                "title": {
                    "type": "string",
                    "minLength": 3,
                    "example": "Amazing Invention"
                }
            }
        },
        "entity.Inventor": {
            "type": "object",
            "required": [
                "email",
                "firstname",
                "lastname"
            ],
            "properties": {
                "age": {
                    "type": "integer",
                    "maximum": 100,
                    "minimum": 18,
                    "example": 30
                },
                "email": {
                    "type": "string",
                    "example": "john.doe@example.com"
                },
                "firstname": {
                    "type": "string",
                    "example": "John"
                },
                "id": {
                    "type": "integer"
                },
                "lastname": {
                    "type": "string",
                    "example": "Doe"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.8.2",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Mini-Go-Server",
	Description:      "API Server for my github project",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
